baseURL = "https://cknotes.kr/"
locale = "ko-KR"
title = "CK notes"
theme = "PaperMod"
paginate = 10
enableRobotsTXT = true

# PaperMod Search
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  env = "production"
  title = "CK notes"
  description = "16년 차 IT 시스템 엔지니어 CK의 실무 인프라(HPE SimpliVity, VME, VMware, Linux, 서버/스토리지) 구축 및 트러블슈팅 경험 기록 노트"
  author = "CK notes"
  DateFormat = "2006-01-02 15:04"
  ShowReadingTime = false
  ShowShareButtons = true
  ShowPostNavLinks = true

[params.analytics.google]
  SiteVerificationTag = "dr0Q6_PYk2R4JOUSa884LZJjb8hrAqlRxTg5j-XnkgY"




[languages.ko]
  label = "Korean"
  weight = 1
  [languages.ko.menu]
    [[languages.ko.menu.main]]
      identifier = "posts"
      name = "Posts"
      url = "/posts/"
      weight = 10
    [[languages.ko.menu.main]]
      identifier = "categories"
      name = "Categories"
      url = "/categories/"
      weight = 15
    [[languages.ko.menu.main]]
      identifier = "search"
      name = "Search"
      url = "/search/"
      weight = 20

    [[languages.ko.menu.main]]
      identifier = "tags"
      name = "Tags"
      url = "/tags/"
      weight = 30
    [[languages.ko.menu.main]]
      identifier = "privacy"
      name = "Privacy Policy"
      url = "/privacy/"
      weight = 40
    [[languages.ko.menu.main]]
      identifier = "about"
      name = "About me"
      url = "/about/"
      weight = 50


[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":git", "date"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]


